# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 210c1585537017dcd1275199c23ea3764a544e68f9e6666e10b7a39d3221f435a3783064808e19f8adb33aec3a60ca0e88fbde170c7a02c721a3fdcf029eeec3

test:
  secret_key_base: 1f743a3f945a3cfcec5171af0a15e60480a6bf551b2259a071f0f7484e2d0724b1463b4ae142dc78fc00d4b15933b7c15668ecb8da8107d3129acb2fff7dd1a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
